export const reportings = [
  {
    SL: "1",
    Name: "Marble & Tile Traders’ Association of Siliguri Vs. C.T.O & Ors.",
    VST: "(2008)14 VST 455",
    Citation: "(2008) 51 STA 97",
    Court: "",
  },
  {
    SL: "2",
    Name: "Prashant Milan (P) Ltd. & Anr. Vs. CCT, West Bengal & Anr.",
    VST: "(2009) 1 CHN 265",
    Citation: "(2008) 52 STA 232 CAL (DB)",
    Court: "",
  },
  {
    SL: "3",
    Name: "Asit Baran Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 25 VST 124",
    Citation: "(2008) 52 STA 234",
    Court: "",
  },
  {
    SL: "4",
    Name: "Rotomac Electricals Pvt. Ltd. Vs. Addl.CCT, West Bengal & Ors.",
    VST: "(2009) 54 STA 342",
    Citation: "",
    Court: "",
  },
  {
    SL: "5",
    Name: "Asit Baran Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 25 VST 143",
    Citation: "(2009) 54 STA 256 CAL (DB)",
    Court: "",
  },
  {
    SL: "6",
    Name: "P.D. Prasad & Sons Pvt. Ltd Vs. ACCT & Ors.",
    VST: "(2009) 25 VST 335",
    Citation: "(2009) 54 STA 277 CAL (DB)",
    Court: "",
  },
  {
    SL: "7",
    Name: "Premier Diesel Pvt Ltd Vs. CCT, WB",
    VST: "(2009) 25 VST 195",
    Citation: "(2008) 52 STA 270",
    Court: "",
  },
  {
    SL: "8",
    Name: "JSK Marketing Private Limited Vs. Sales Tax Officer & Ors.",
    VST: "(2009) 26 VST 272",
    Citation: "(2010) 55 STA 178 WBTT",
    Court: "",
  },
  {
    SL: "9",
    Name: "Pankaj Gupta Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 28 VST 57",
    Citation: "",
    Court: "",
  },
  {
    SL: "10",
    Name: "Sri Pradip Kumar Sanganeria Vs. CTO, Narendra Dutta Sarani Charge\n & Ors.",
    VST: "(2010) 55 STA 30 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "11",
    Name: "Nand Kishore Garg Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 30 VST 101 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "12",
    Name: "Howrah Tax Payers’ Association Vs. Government of West Bengal.",
    VST: "(2010) 31 VST 458",
    Citation: "(2009) 53 STA 276 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "13",
    Name: "ICICI Bank Ltd. Vs. JCST, Central Section & Ors.",
    VST: "(2010) 31 VST 178",
    Citation: "(2011) 59 STA 107 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "14",
    Name: "Indian Jute Mills’ Association Vs. DCST, CD & Ors.",
    VST: "(2010) 31 VST 108",
    Citation: "(2010) 55 STA 38 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "15",
    Name: "Gourangalal Chatterjee Vs. State of West Bengal",
    VST: "(2010) 32 VST 355 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "16",
    Name: "Bharti Airtel Ltd & Anr.Vs. ACST, Salt Lake Charge & Ors.",
    VST: "(2010) 34 VST 202",
    Citation: "(2010) 56 STA 184 WBTT",
    Court: "",
  },
  {
    SL: "17",
    Name: "BOC India Ltd. Vs. WBCTARB & Ors",
    VST: "(2010) 34 VST 448 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "18",
    Name: "Nursing Vanijya Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 34 VST 18 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "19",
    Name: "Calcutta Iron & Engineering Co. Pvt. Ltd Vs. ACCT, Corporate\n Division & Ors.",
    VST: "(2010) 55 STA 186 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "20",
    Name: "Sunita Lakhotia (Smt.) Vs. Sales Tax Officer & Ors.",
    VST: "(2010) 34 VST 373",
    Citation: "(2010) 55 STA 234 WBTT",
    Court: "",
  },
  {
    SL: "21",
    Name: "Builders’ Association of India Vs. State of West Bengal",
    VST: "(2010) 35 VST 22",
    Citation: "(2010) 55 STA 224 WBTT (FB)",
    Court: "WBTT (FB)",
  },
  {
    SL: "22",
    Name: "Himanka Kumar Paul Vs. Additional CCT,West Bengal & Ors.",
    VST: "(2011) 38 VST 433 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "23",
    Name: "Ashok Kumar Ghosh Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 41 VST 97 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "24",
    Name: "Epitome Petrochemicals Pvt. Ltd Vs. CCT West Bengal & Ors.",
    VST: "(2011) 41 VST 22",
    Citation: "(2011) 58 STA 95 WBTT",
    Court: "",
  },
  {
    SL: "25",
    Name: "JNRT Commercial (P) Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2011) 57 STA 237 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "26",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Deputy Commissioner of Sales Tax &\n Ors.",
    VST: "(2011) 42 VST 31 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "27",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Senior Joint Commissioner of\n Commercial Tax & Ors.",
    VST: "(2011) 42 VST 34 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "28",
    Name: "Denzong Wines (Pvt.) Ltd. Vs. Senior Joint Commissioner of\n Commercial Tax & Ors.",
    VST: "(2011) 42 VST 44 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "29",
    Name: "Maple Exports Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 42 VST 419 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "30",
    Name: "Super Spirit Warehouse Vs. State of West Bengal & Ors.",
    VST: "(2011) 57 STA 222 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "31",
    Name: "Maple Exports Pvt. Ltd. Vs. Sales Tax Officer & Ors.",
    VST: "(2011) 42 VST 424 (2011) 58 STA 168 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "32",
    Name: "W.B. Foreign Liquor “off” and “on” Shop Owners’ Association &\n Another Vs. The Govt. of West Bengal & Ors.",
    VST: "(2011) 59 STA 27 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "33",
    Name: "Debabrata Roy Choudhury Vs. STO, Burdwan Charge & Anr.",
    VST: "(2012) 49 VST 231 STA 104",
    Citation: "",
    Court: "",
  },
  {
    SL: "34",
    Name: "Frostees Exports Pvt Ltd Vs. DCCT, Corporate Division & Ors.",
    VST: "(2012) 50 VST 392 (2011) 57 STA 36 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "35",
    Name: "Deb Scientific Vs. ACST, Central Section & Ors.",
    VST: "(2012) 52 VST 191 (2012) 60 STA 207 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "36",
    Name: "Hasmukh Parekh Vs. ASTO & Ors.",
    VST: "(2012) 52 VST 195 (2012) 60 STA 114 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "37",
    Name: "Angus Jute Works of the Angus Co. Ltd JCCT, Corporate Division &\n Ors",
    VST: "(2012) 53 VST 99 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "38",
    Name: "Angus Jute Works of the Angus Co. Ltd JCCT, Corporate Division &\n Ors",
    VST: "(2012) 53 VST 106 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "39",
    Name: "Auto Hitech (P) Ltd. Vs. ACCT, Corporate Division & Ors.",
    VST: "(2010) 36 VST 198 (2012) 60 STA 17 WBTT (FB)",
    Citation: "",
    Court: "WBTT (FB)",
  },
  {
    SL: "40",
    Name: "Durgapada Sahoo Vs. State of West Bengal",
    VST: "2008 (2) CLJ (Cal) 80 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "41",
    Name: "ACCT, Corporate Division & Ors. Vs. Sambhu Prasad Agarwal",
    VST: "(2012) 60 STA 92 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "42",
    Name: "Epitome Petrochemicals Pvt. Ltd Vs. STO & Ors.",
    VST: "(2012) 54 VST 20 WBTT",
    Citation: "",
    Court: "",
  },
  {
    SL: "42A",
    Name: "Santosh Kumar Chowdhury Vs. Sr.JCCT Asansol Circle & Ors.",
    VST: "(2012) 55 VST 472 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "43",
    Name: "Sajan Kumar Bansal Vs. STO, Fairly Place Charge & Ors.",
    VST: "(2010) 2 CHN (Cal) 135 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "44",
    Name: "Gorachand Rakshit Vs. STO, Manohar Katra Charge & Ors.",
    VST: "(2010)1 CHN (Cal) 381 CAL",
    Citation: "",
    Court: "",
  },
  {
    SL: "45",
    Name: "New Ghosh Builders Vs. SrJCST, Durgapore Circle & Ors.",
    VST: "(2012) 56 VST 154 (2012) 60 STA 149 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "46",
    Name: "Trimurti Industries Ltd. Vs. STO, Siliguri Range & Ors.",
    VST: "(2012) 54 VST 405 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "47",
    Name: "Prabhash Chand Jain Vs. ACCT",
    VST: "(2012) 55 VST 306 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "48",
    Name: "Creative Polypack Ltd Vs. Addl. CCT & Ors",
    VST: "(2013) 61 STA 151 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "49",
    Name: "Delhi Assam Roadways Corporation Ltd. Vs. STO Siliguri Range &\n Ors.",
    VST: "(2013) 59 VST 433 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "50",
    Name: "Akshay Ispat & Ferro Alloys Pvt. Ltd. Vs. STO, Siliguri Range",
    VST: "(2013) 60 VST 274 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "51",
    Name: "Cipla Ltd. Vs. DCCT, Corporate Division & Ors.",
    VST: "(2013) 61 VST 445 (2013) 62 STA 194 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "52",
    Name: "Deepak Agarwal Vs. DCST, Manohardas Katra Charge & Ors.",
    VST: "(2013) 62 STA 7 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "53",
    Name: "PCM Tea Processing Pvt. Ltd. Vs. Assistant Commissioner Commercial\n Taxes & Ors.",
    VST: "(2013) 63 VST 288 (2014) 3 CHN (Cal) 258 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "54",
    Name: "PCM Tea Processing Pvt. Ltd. Vs. Assistant Commissioner Commercial\n Taxes & Ors.",
    VST: "(2013) 63 VST 293 (2013) 62 STA 29 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "55",
    Name: "ACST, Purulia Range Vs. Maa Chhinamastika Steel & Power Ltd.",
    VST: "(2013) 61 STA 264 CAL (DB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "56",
    Name: "Lalit Kumar Khaitan & Anr. Vs. JCCT, Barrackpore Range & Ors.",
    VST: "(2013) 61 STA 271 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "57",
    Name: "Gouranga Parbati Tea Co. Pvt. Ltd. Vs. A.I.T.O. Siliguri Charge &\n Ors",
    VST: "(2013) 62 STA 271 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "58",
    Name: "Kores (India) Ltd. & Anr. Vs. STO Duburdih Check Post & Ors.",
    VST: "(2013) 62 STA 180 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "59",
    Name: "Sri Jagannath Poddar Vs. STO & Ors.",
    VST: "(2014) 2 VST-OL 534 (2015) 65 STA 32 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "60",
    Name: "Braja Gopal Saha Vs. STO & Ors.",
    VST: "(2014) 2 VST-OL 649 (2014) 64 STA 255 CAL (SB)",
    Citation: "",
    Court: "",
  },
  {
    SL: "61",
    Name: "Spasht Marketing Pvt. Ltd Vs. ASTO, Bureau of Investigation & Ors.",
    VST: "(2014) 71 VST 131 (2014) 64 STA 161 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "62",
    Name: "Buddhadeb Maity & Anr Vs. Sr.JCCT/ Medinipore Circle & Ors.",
    VST: "(2014) 63 STA 247 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "63",
    Name: "Rotomac Electrical Pvt. Ltd. Vs. Addl.CCT & Ors.",
    VST: "(2014) 63 STA 276 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "64",
    Name: "Sovan Das Vs. STO Behala Charge & Ors.",
    VST: "(2014) 71 VST 462 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "65",
    Name: "Kamala Board Box Pvt. Ltd. Vs. DCCT, 24 Pgs. Circle & Ors.",
    VST: "(2014) 64 STA 195 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "66",
    Name: "Kanknarrah Co. Ltd. v. Commercial Tax Officer",
    VST: "(2014) 3 VST-OL 540 (2014) 64 STA 281 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "67",
    Name: "Rina Dey v. Sales Tax Officer",
    VST: "(2014) 3 VST-OL 537 (2015) 65 STA 169 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "68",
    Name: "Deepak Agarwal Vs. DCST, Manohardas Katra Charge & Ors",
    VST: "(2014) 3 VST-OL 503 WBTT",
    Citation: "",
    Court: "WBTT",
  },
  {
    SL: "69",
    Name: "Himanka Kumar Paul Vs. Additional CCT,West Bengal & Ors.",
    VST: "(2014) 64 STA 288 WBTT",
    Citation: "",
    Court: "WBTT",
  },
];
